name: Build and Deploy

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=schedule,enable=true,pattern={{date 'YYYYMMDD-hhmmss' tz='${{ vars.TZ }}'}}
            type=semver,enable=false
            type=pep440,enable=false
            type=match,enable=false
            type=edge,enable=false
            type=ref,enable=false
            type=sha,enable=false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          
      - name: Remote SSH and update container with latest docker image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_VM_HOST }}
          username: ${{ vars.SSH_VM_USER }}
          key: ${{ secrets.SSH_VM_KEY }}
          script: |
            docker stop ${{ github.event.repository.name }}
            docker rm ${{ github.event.repository.name }}
            docker pull ghcr.io/${{ github.repository }}
            docker run --name ${{ github.event.repository.name }} \
              --detach \
              -p ${{ vars.PORT }}:3000 \
              --restart unless-stopped \
              ghcr.io/${{ github.repository }}
