name: Build and Deploy

on:
  push:
    branches:
      - "dodyagung.com"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            # ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          flavor: |
            latest=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_vm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH and update container with latest docker image
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_VM_HOST }}
          username: ${{ vars.SSH_VM_USER }}
          key: ${{ secrets.SSH_VM_KEY }}
          script: |
            docker stop ${{ github.event.repository.name }}
            docker rm ${{ github.event.repository.name }}
            docker pull ${{ github.repository }}
            docker run --name ${{ github.event.repository.name }} \
              --detach \
              -p ${{ vars.PORT }}:3000 \
              --restart unless-stopped \
              ${{ github.repository }}
