name: Build and Deploy

on: push

jobs:
  prepare-tags:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set.outputs.timestamp }}
    steps:
      - id: set
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare-tags
    strategy:
      matrix:
        include:
          - arch: amd64
            os: ubuntu-latest
          - arch: arm64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ needs.prepare-tags.outputs.timestamp }}
          labels: true

      - name: Build and push for ${{ matrix.arch }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  merge-manifest:
    needs: [prepare-tags, build]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge multi-arch manifest
        run: |
          REPO=ghcr.io/${{ github.repository }}
          for tag in latest ${{ needs.prepare-tags.outputs.timestamp }}; do
            echo "Merging manifest for tag: $tag"
            docker buildx imagetools create \
              --tag "$REPO:$tag" \
              "$REPO:$tag"
          done

  deploy:
    runs-on: ubuntu-latest
    needs: merge-manifest
    steps:
      - name: Deploy to remote server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SSH_VM_HOST }}
          username: ${{ vars.SSH_VM_USER }}
          key: ${{ secrets.SSH_VM_KEY }}
          script: |
            docker stop ${{ github.event.repository.name }} || true
            docker rm ${{ github.event.repository.name }} || true
            docker pull ghcr.io/${{ github.repository }}:latest
            docker run --name ${{ github.event.repository.name }} \
              --detach \
              -p ${{ vars.PORT }}:3000 \
              --restart unless-stopped \
              ghcr.io/${{ github.repository }}:latest
